import Head from "next/head";
import Image from "next/image";
import Cta from "../components/Cta";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import DisplayCards from "../components/DisplayCards";
import Navbar from "../components/Navbar";
import Explore from "../components/Explore";
import AdSection from "../components/Bigad";
import News from "../components/News";
import Month from "../components/Month";
import Artists from "../components/Artists";
import Values from "../components/Values";

export default function Home() {
  return (
    <div>
      <Head>
        <title>FENDER+</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    <Hero/>
    <Values/>
    <AdSection/>
    <News/>
    <Month/>
    <Artists/>
    <Explore/>
    <DisplayCards/>
    <Cta/>
    <Footer/>
    </div>
  );
}
